includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/FSL-QuickBoost.yaml
  - backbones/cnnencoder.yaml

classifier:
  name: QuickBoost
  kwargs:
    inputsize: 64
    hidden_size: 8


backbone:
  name: CNNEncoder
  kwargs:
 # 不需要参数